/*
 * File: app/store/BusinessStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WitWu.store.BusinessStore', {
    extend: 'Ext.data.Store',

    requires: [
        'WitWu.model.Business'
    ],

    config: {
        data: [
            {
                id: 200,
                ownerName: 'Len',
                latitude: 100,
                longitude: 100,
                taskName: 'Run 5 miles'
            },
            {
                id: 201,
                ownerName: 'Len',
                latitude: 100,
                longitude: 100,
                taskName: 'Present marketing plan'
            },
            {
                id: 202,
                ownerName: 'Force',
                latitude: 100,
                longitude: 100,
                taskName: 'Research potential advertisement platforms'
            },
            {
                id: 203,
                ownerName: 'Force',
                latitude: 100,
                longitude: 100,
                taskName: 'Get Groceries'
            },
            {
                id: 204,
                ownerName: 'Jedi',
                latitude: 100,
                longitude: 100,
                taskName: 'Demo App'
            },
            {
                id: 205,
                ownerName: 'Jedi',
                latitude: 100,
                longitude: 100,
                taskName: 'Growth Plan'
            },
            {
                id: 206,
                ownerName: 'Jedi',
                latitude: 100,
                longitude: 100,
                taskName: 'Meetign with Chris + Len'
            }
        ],
        groupField: 'ownerName',
        model: 'WitWu.model.Business',
        storeId: 'BusinessStore',
        grouper: {
            groupFn: function(item) {
                if (item && item.data.userName) {
                    return item.data.userName;
                }
                else {
                    return '';
                }
            },
            sortProperty: 'userName'
        }
    }
});