/*
 * File: app/view/MainTabView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WitWu.view.MainTabView', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',

    config: {
        activeItem: 1,
        items: [
            {
                xtype: 'list',
                title: 'Todo',
                iconCls: 'star',
                itemTpl: [
                    '<div>{taskName}</div>'
                ],
                store: 'BusinessStore',
                grouped: true,
                onItemDisclosure: true,
                items: [
                    {
                        xtype: 'container'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Nearby',
                iconCls: 'maps',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'map',
                                height: '100%',
                                useCurrentLocation: true
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Features',
                iconCls: 'info',
                items: [
                    {
                        xtype: 'container',
                        styleHtmlContent: true,
                        tpl: [
                            '<div> ',
                            '    Todo list <br />',
                            '    Todo by Date <br />',
                            '    Todo by Location <br />',
                            '    Nearby Reminders <br />',
                            '    Cloud Enabled <br />',
                            '    Share with Friends <br />',
                            '    Accept/Reject Todo\'s <br />',
                            '</div>'
                        ],
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'label',
                                centered: false,
                                html: '<div> <h2> Features </h2>     Todo list <br /> Add Todo <br/>     Todo by Date <br />     Todo by Location <br />     Nearby Reminders <br />     Cloud Enabled <br />     Share with Friends <br />     Accept/Reject Todo\'s <br /> </div>'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'searchfield'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.Msg.alert('Task added!','Good-luck!');
                        },
                        iconCls: 'add'
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom',
            layout: {
                pack: 'center',
                type: 'hbox'
            }
        }
    }

});