/*
 * File: app/controller/Business.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WitWu.controller.Business', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            todoList: '#todoList'
        },

        control: {
            "#todoList": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        console.log("Hello!");
        var myStore = Ext.StoreMgr.get('BusinessStore'); //works - get reference to
        var myRecord = dataview.getStore().getAt(index);
        myStore.remove(record);
    },

    launch: function() {
        //var me = this;



    }

});